M48
; DRILL file {KiCad 8.0.4} date 2024-09-03T11:52:41+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-03T11:52:41+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.909Y-3.937
X4.9168Y-2.7559
T2
X4.1339Y-2.1654
X4.1339Y-4.5472
X7.6772Y-2.1654
X7.6772Y-4.5276
M30
